"""empty message

Revision ID: 8e2b8be25c71
Revises: da36c7235a93
Create Date: 2024-11-20 23:20:47.186500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2b8be25c71'
down_revision: Union[str, None] = 'da36c7235a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_hash', sa.String(), nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'login_hash')
    # ### end Alembic commands ###
