"""Add autoincrement to user_progress id

Revision ID: 9d4a77003f37
Revises: 3ed93aeb6e79
Create Date: 2024-11-23 13:39:31.190044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4a77003f37'
down_revision: Union[str, None] = '3ed93aeb6e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
